name: Gerar APK Direto
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o Projeto
        uses: actions/checkout@v4

      - name: Instalando Node e Java
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Instalando Dependencias
        run: npm install --legacy-peer-deps

      - name: Criando a Pasta Android
        # Esse comando cria a estrutura de aplicativo que o GitHub precisa ver
        run: npx expo prebuild --platform android

      - name: Fabricando o APK (Gradlew)
        # Aqui é onde o arquivo .apk é cozinhado de verdade
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: App-Instalador-TRAMPO-CERTO
          path: android/app/build/outputs/apk/debug/app-debug.apk
