name: Gerar APK Direto
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando Projeto
        uses: actions/checkout@v4

      - name: Configurando Ambiente
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalando Ferramentas
        run: |
          npm install -g expo-cli
          npm install --legacy-peer-deps

      - name: Preparando Estrutura Android
        # Esse comando cria a pasta que o GitHub não está achando
        run: npx expo prebuild --platform android --no-install

      - name: Fabricando o APK
        # Comando para gerar o instalador final
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Entregar APK para o Adão
        uses: actions/upload-artifact@v4
        with:
          name: Instalador-Trampo-Certo
          path: android/app/build/outputs/apk/debug/app-debug.apk
