name: Gerar Pacote Final
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Coletando arquivos
        uses: actions/checkout@v4

      - name: Criando Instalador ZIP
        # Este comando junta o seu App.js e tudo o que mandou num ficheiro sรณ
        run: zip -r Projeto_Trampo_Certo.zip . -x "*.git*"

      - name: Liberar para Download
        uses: actions/upload-artifact@v4
        with:
          name: Pacote-Pronto-Adao
          path: Projeto_Trampo_Certo.zip
