name: Gerar APK Oficial
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pegando o Código
        uses: actions/checkout@v4

      - name: Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalando Dependências
        run: npm install --legacy-peer-deps

      - name: Gerar Bundle Android
        # Esse comando transforma seu App.js no arquivo que o Android entende
        run: npx react-native bundle --platform android --dev false --entry-file App.js --bundle-output index.android.bundle

      - name: Criar APK (Debug)
        # Comando para fabricar o arquivo .apk de verdade
        run: |
          mkdir -p android/app/src/main/assets
          cp index.android.bundle android/app/src/main/assets/
          cd android && ./gradlew assembleDebug

      - name: Entregar APK para o Adão
        uses: actions/upload-artifact@v4
        with:
          name: Trampo-Certo-Instalador
          path: android/app/build/outputs/apk/debug/app-debug.apk
