name: Gerar APK Oficial
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pegando o Código
        uses: actions/checkout@v4

      - name: Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalando Dependências
        run: npm install --legacy-peer-deps

      - name: Construindo o Projeto (Android)
        run: |
          # Esse comando prepara os arquivos para virar APK
          npx expo export --platform android

      - name: Gerar Artefato APK
        uses: actions/upload-artifact@v4
        with:
          name: TrampoCerto-Instalador-APK
          # O caminho onde o arquivo final fica guardado
          path: dist/*.apk
